export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const RESQUEST_ROBOTS_PENDING = 'RESQUEST_ROBOTS_PENDING'
export const RESQUEST_ROBOTS_SUCCESS = 'RESQUEST_ROBOTS_SUCCESS'
export const RESQUEST_ROBOTS_FAILED = 'RESQUEST_ROBOTS_FAILED'
